# Mean - Median - Mode - Skewwness 

In [1]:
import numpy as np
from scipy import stats

In [2]:
age = [20, 22, 25, 25, 27, 27, 27, 29, 30, 31, 121]

In [3]:
np.mean(age)

34.90909090909091

In [4]:
np.median(age)

27.0

In [5]:
stats.mode(age)

ModeResult(mode=array([27]), count=array([3]))

In [6]:
stats.mode(age)[0]

array([27])

In [7]:
import pandas as pd

In [8]:
data = {"D1":[135, 137, 136, 138, 138],

              "D2":[43,   42, 42, 42, 42],

              "D3":[72, 73, 72, 72, 73],

              "D4":[100, 102, 100, 103, 104]};

In [9]:
df = pd.DataFrame(data)

In [10]:
df

D1  D2  D3   D4
0  135  43  72  100
1  137  42  73  102
2  136  42  72  100
3  138  42  72  103
4  138  42  73  104

In [11]:
df.mean()

D1    136.8
D2     42.2
D3     72.4
D4    101.8
dtype: float64

In [12]:
df["D2"].mean()

42.2

In [13]:
df["D1"].mode()

0    138
dtype: int64

In [14]:
df["D4"].median()

102.0

# Dispersion

In [15]:
age = [20, 22, 25, 25, 27, 27, 27, 29, 30, 31]

In [16]:
np.std(age)

3.2572994949804666

In [17]:
age2 = [20, 22, 25, 25, 27, 27, 27, 29, 30, 31, 121]

In [18]:
np.std(age2)

27.400910885504736

In [20]:
#range
np.max(age2) - np.min(age2)

101

In [21]:
#variance
np.var(age2)

750.809917355372

In [22]:
# IQR
from scipy.stats import iqr

In [23]:
iqr(age2)

4.5

In [25]:
#Q1 ve Q3 hesabı

q1 = np.percentile(age2, 25)
q1

25.0

In [26]:
q3 = np.percentile(age2, 75)
q3

29.5

In [27]:
iqr = q3 - q1
iqr

4.5

In [28]:
np.percentile(age2, 50)

27.0

In [29]:
np.median(age2)

27.0

# Skewness and Kurtosis

In [30]:
#kurtosis
stats.kurtosis(age2)

5.876609699981859

In [31]:
#skewness
stats.skew(age2)

2.778572264050739

# Population and Sample

In [37]:
np.random.seed(101)

population = np.random.randint(0,100,size=1000)

In [38]:
population

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40,  4, 63, 40, 60, 92, 64,  5,
       12, 93, 40, 49, 83,  8, 29, 59, 34, 44, 72, 19, 10, 76, 95, 87,  0,
       73,  8, 62, 36, 83, 99, 28, 63,  7, 10, 52, 56, 38, 73, 52, 18, 71,
       15, 44,  0, 12, 17, 75, 79, 97, 93, 24, 36, 63, 19, 35, 30, 10, 60,
       20, 27,  8, 86, 26, 87, 46, 47, 54, 86,  9, 45,  2, 18, 58, 92, 11,
       10, 94, 35, 28,  3, 83, 84, 47, 14, 69, 60, 69, 51,  6, 88, 71, 68,
       23, 35, 79, 98, 67, 82, 57, 77, 46,  3, 46, 29, 86, 21, 21, 81, 23,
       94, 71, 20, 27, 75,  5, 49, 86, 89, 63, 82, 77,  3, 56, 14, 49, 87,
       52, 13, 47, 49, 24, 20, 64, 52, 60, 47, 29, 60, 53, 11, 40, 91, 45,
       97, 24, 36, 38,  9, 52, 67, 43,  1, 79, 68, 68, 61, 18, 51, 14, 28,
       17, 87, 46, 52, 16, 70, 71, 84, 10, 62, 96, 57, 23, 86, 85, 26, 76,
       66, 54, 17, 65, 57, 89,  2, 80, 50, 66, 88, 79, 93,  6, 92, 42, 22,
       20, 25, 97, 54, 71, 72, 80, 93, 64, 63, 80, 38, 45, 35, 25, 95, 75,
       72, 11, 76, 79, 50

In [39]:
#sampling
np.random.seed(51)
sample = np.random.choice(population,100)

In [40]:
sample

array([79, 26, 84, 16, 92, 29, 96, 65, 45, 17,  9, 85, 33,  4, 47, 93, 19,
       14, 20, 68, 43, 40, 19, 92, 43,  8, 75, 65, 55, 46, 15, 74, 32, 59,
       87, 12, 87, 43, 19, 19, 26, 49, 57, 47,  5, 68, 52, 56, 78, 34, 11,
       95, 65, 55, 21, 38, 52, 17, 31,  5, 81,  5, 72,  8, 49, 20, 19, 35,
       27, 55, 44, 80, 18, 70, 82, 40, 76,  3, 48, 28, 47, 80, 69, 41, 41,
       84, 54, 60, 62, 16, 64, 41, 28, 77, 90, 39, 27, 16, 20, 28])

In [41]:
population.mean()

50.372

In [42]:
sample.mean()

45.8

In [43]:
sample_means = []
for i in range(100):
  sample = np.random.choice(population, 100)
  sample_means.append(sample.mean())

sample_means

[52.93,
 52.71,
 51.48,
 49.02,
 50.72,
 45.84,
 48.77,
 48.41,
 54.01,
 44.87,
 51.72,
 51.65,
 54.57,
 48.83,
 44.41,
 49.63,
 49.15,
 50.02,
 48.74,
 52.77,
 51.26,
 49.28,
 52.28,
 50.7,
 52.81,
 46.22,
 54.3,
 46.9,
 49.29,
 46.83,
 49.81,
 45.98,
 53.15,
 50.75,
 41.74,
 47.2,
 51.9,
 48.24,
 52.57,
 50.34,
 45.78,
 48.94,
 56.4,
 51.11,
 50.95,
 44.03,
 51.2,
 47.32,
 53.74,
 48.19,
 54.51,
 47.38,
 50.3,
 49.49,
 52.27,
 53.45,
 53.87,
 52.99,
 54.08,
 53.49,
 52.23,
 47.72,
 49.48,
 53.17,
 51.83,
 52.98,
 47.68,
 54.8,
 50.11,
 50.31,
 52.07,
 49.52,
 51.08,
 53.73,
 47.46,
 48.05,
 46.97,
 47.07,
 50.67,
 46.96,
 49.74,
 50.45,
 50.02,
 49.99,
 48.17,
 48.72,
 48.8,
 53.64,
 48.65,
 55.24,
 45.34,
 52.11,
 51.73,
 51.0,
 52.41,
 49.71,
 49.24,
 48.12,
 49.51,
 43.78]

In [44]:
np.mean(sample_means)

50.11549999999999